### ISSUE TITLE
Move Config to Toml / or allow toml configuration

### ISSUE THREAD

**Issue by Daholli** [Jas-SinghFSU/HyprPanel#433]
**Is your feature request related to a problem? Please describe.**
while nixifying my current configuration I came across the issue hat the json config just uses strings as keys, rather than nested configs

such as 
```json
  "menus.dashboard.shortcuts.left.shortcut1.command": "",
  "menus.dashboard.shortcuts.left.shortcut1.icon": "",
  "menus.dashboard.shortcuts.left.shortcut1.tooltip": ""
```

instead of 
```json
"menus" : {
  "dashboard" : {
    "shortcuts" : {...}
  }
}
```
This leads to lots of pain when trying to adjust things in text

**Describe the solution you'd like**
When using toml all of this looks a lot nicer and should still be very easy to generate and adapt on the fly (I will look into this maybe open a pr if I manage to get it working)

```toml
scalingPriority = "hyprland"
tear = true

[bar]
scrollSpeed = 0

[bar.clock]
format = "%a %b %d  %H:%M:%S"

[bar.customModules.cpu]
icon = " "
label = true
leftClick = "kitty --hold btop"
```
