### ISSUE TITLE
Add padding options for dashboard, power menu, notification center popups

### ISSUE THREAD

**Issue by Chamal1120** [Jas-SinghFSU/HyprPanel#653]
**Problem**: At the time this writing there is no option to move the popups like dashboard or notification center away from the edge of the screen which makes it is not good looking when using with the floating bar option as it leaves gap from left and right side of the bar.

**Preferred solution**: Provide an option to adjust the padding or distance from the edges so we can position them the according to our liking.

Please look at the screenshots below to get an idea.
![2024-12-28-194420_hyprshot](https://github.com/user-attachments/assets/f530c05b-3bbf-4ae7-98ff-3797801a6ff3)
![2024-12-28-194408_hyprshot](https://github.com/user-attachments/assets/13ebeffe-3ffb-47ca-84fa-102a0c280adb)

**Comment by Yilmaz4** [comment]
Any update on this? I'm seeing screenshots where there's a gap, but I can't find where to set it

**Comment by Chamal1120** [comment]
@Yilmaz4 let me know too if you find any solution

**Comment by corigne** [comment]
I agree that adding position adjustments to the settings would be good, however in the meantime, here's some scss you can put in `~/config/hyprpanel/modules.scss`.

```scss
/* ~/.config/hyprpanel/modules.scss */
.menu-items {
  margin-top: 0.25em;
}

.dashboard-content-container {
  margin-left: 2em;
  margin-top: 0.25em;
}

.calendar-content-container {
  margin-right: 2em;
  margin-top: 0.25em;
}

.notification-menu-content {
  margin-right: 2em;
  margin-top: 0.25em;
}
```

I searched the codebase a bit to find which classes did what, but as said before, which was a bit cumbersome, but it suffices for now.
